# Generated by Django 3.1.5 on 2021-02-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210213_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalist',
            old_name='last_time',
            new_name='last_name',
        ),
    ]
